# Generated by Django 3.2.8 on 2021-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc_api', '0002_alter_consultant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
