# Generated by Django 3.2.8 on 2021-10-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc_api', '0002_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
