# Generated by Django 3.2.8 on 2021-10-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc_api', '0004_questionset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1028, null=True)),
                ('hint', models.TextField(blank=True, max_length=1028, null=True)),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdoc_api.question')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdoc_api.consultant')),
            ],
        ),
    ]
