# Generated by Django 3.2.8 on 2021-11-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc_api', '0007_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_question', to='vdoc_api.question')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_question', to='vdoc_api.question')),
            ],
        ),
    ]
