# Generated by Django 3.2.8 on 2021-11-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc_api', '0010_auto_20211117_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_q',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vdoc_api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vdoc_api.question'),
        ),
    ]
