name: Build docker container

on:
  pull_request:
    branches: [master]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build .
      - run: docker compose up

