name: remote ssh command
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: docker build .
      - run: docker-compose up -d --build
      - run: docker-compose exec -T web python manage.py test
      - run: docker-compose down
  build:
    needs: [test]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to ${{ secrets.HOST }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd VirtualDoctor
          git pull
          docker-compose down
          docker-compose up -d --build